import { Tool } from "@/types";

export const tools: Tool[] = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "De meest populaire AI-assistent ter wereld",
    description:
      "ChatGPT van OpenAI is de meest bekende AI-chatbot en tekstgenerator. Geschikt voor schrijven, coderen, analyseren en vrijwel alles met tekst.",
    logo: "/logos/chatgpt.svg",
    website: "https://chat.openai.com",
    affiliateUrl: "https://chat.openai.com/?ref=besteai",
    category: ["Tekstgeneratie", "AI-assistent", "Coderen"],
    pricing: {
      free: true,
      freeTier: "Beperkt gratis gebruik",
      startingPrice: "20",
      currency: "USD",
    },
    rating: 4.8,
    pros: [
      "Zeer veelzijdig – van e-mails tot code",
      "Gratis basisversie beschikbaar",
      "Uitstekende instructie-opvolging",
      "Grote pluginbibliotheek (Plus)",
      "Regelmatige updates en verbeteringen",
    ],
    cons: [
      "Kan verouderde informatie geven (kennisgrens)",
      "Plus-abonnement verplicht voor GPT-4",
      "Soms te voorzichtig bij gevoelige onderwerpen",
    ],
    features: [
      "GPT-4o model",
      "Beeldgeneratie (DALL-E)",
      "Plugins & GPTs",
      "Code interpreter",
      "Browsefunctie",
      "Mobiele app",
    ],
    bestFor: "Iedereen die dagelijks met tekst werkt",
    badge: "Populair",
    publishedAt: "2024-01-15",
    updatedAt: "2024-04-01",
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Veilige AI van Anthropic met lange context",
    description:
      "Claude van Anthropic is een AI-assistent die uitblinkt in lange documenten verwerken, nuancé schrijven en veilig redeneren. Ideaal voor professionals.",
    logo: "/logos/claude.svg",
    website: "https://claude.ai",
    affiliateUrl: "https://claude.ai/?ref=besteai",
    category: ["AI-assistent", "Tekstgeneratie", "Analyse"],
    pricing: {
      free: true,
      freeTier: "Beperkt dagelijks gebruik",
      startingPrice: "20",
      currency: "USD",
    },
    rating: 4.7,
    pros: [
      "200K token contextvenster",
      "Uitstekend in nuancé schrijven",
      "Veilig en betrouwbaar",
      "Goed in lange documenten analyseren",
      "Gratis tier beschikbaar",
    ],
    cons: [
      "Geen beeldgeneratie",
      "Minder plugins dan ChatGPT",
      "Soms te voorzichtig",
    ],
    features: [
      "200K context window",
      "Document upload",
      "Claude 3.5 Sonnet",
      "Projecten & herinneringen",
      "API toegang",
    ],
    bestFor: "Professionals die lange documenten verwerken",
    badge: "Aanbevolen",
    publishedAt: "2024-02-01",
    updatedAt: "2024-04-01",
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "Beste AI voor professionele beeldgeneratie",
    description:
      "Midjourney genereert via Discord adembenemende AI-afbeeldingen. De absolute top voor kunstenaars, designers en marketeers die visuele content nodig hebben.",
    logo: "/logos/midjourney.svg",
    website: "https://midjourney.com",
    affiliateUrl: "https://midjourney.com/?ref=besteai",
    category: ["Beeldgeneratie", "Design", "Creativiteit"],
    pricing: {
      free: false,
      startingPrice: "10",
      currency: "USD",
    },
    rating: 4.9,
    pros: [
      "Ongekende beeldkwaliteit",
      "Enorme stijlvariatie",
      "Actieve community",
      "Consistent hoge output",
      "V6 model is revolutionair",
    ],
    cons: [
      "Geen gratis tier meer",
      "Werkt via Discord (wennen)",
      "Beperkte controle over specifieke details",
      "Privacy: afbeeldingen zijn standaard publiek (basisplan)",
    ],
    features: [
      "Midjourney V6",
      "Inpainting & outpainting",
      "Variaties genereren",
      "Upscaling",
      "Web interface",
    ],
    bestFor: "Designers, marketeers en creatieve professionals",
    badge: "Beste Waarde",
    publishedAt: "2024-01-20",
    updatedAt: "2024-04-01",
  },
  {
    slug: "perplexity",
    name: "Perplexity AI",
    tagline: "AI-zoekmachine met bronvermelding",
    description:
      "Perplexity combineert AI met realtime zoeken en geeft altijd bronvermeldingen. Ideaal voor onderzoek, fact-checking en actuele informatie.",
    logo: "/logos/perplexity.svg",
    website: "https://perplexity.ai",
    affiliateUrl: "https://perplexity.ai/?ref=besteai",
    category: ["Zoeken", "Onderzoek", "AI-assistent"],
    pricing: {
      free: true,
      freeTier: "Onbeperkt gratis basisgebruik",
      startingPrice: "20",
      currency: "USD",
    },
    rating: 4.6,
    pros: [
      "Altijd actuele informatie",
      "Bronvermeldingen bij elk antwoord",
      "Gratis uitgebreid beschikbaar",
      "Ideaal voor onderzoek",
      "Ondersteunt meerdere zoekmodellen",
    ],
    cons: [
      "Minder geschikt voor creatief schrijven",
      "Pro vereist voor beste modellen",
    ],
    features: [
      "Realtime zoeken",
      "Bronvermeldingen",
      "Pro Search (Sonar Pro)",
      "Bestandsupload",
      "Spaces voor projecten",
    ],
    bestFor: "Onderzoekers en fact-checkers",
    publishedAt: "2024-02-15",
    updatedAt: "2024-04-01",
  },
  {
    slug: "jasper",
    name: "Jasper AI",
    tagline: "AI-schrijftool voor marketing en bedrijven",
    description:
      "Jasper is de toonaangevende AI-schrijfassistent voor marketing teams. Met honderden templates en merkgeheugen schrijft Jasper consistent in jouw stijl.",
    logo: "/logos/jasper.svg",
    website: "https://jasper.ai",
    affiliateUrl: "https://jasper.ai/?ref=besteai",
    category: ["Contentmarketing", "Tekstgeneratie", "SEO"],
    pricing: {
      free: false,
      freeTier: "7 dagen gratis proberen",
      startingPrice: "39",
      currency: "USD",
    },
    rating: 4.4,
    pros: [
      "Specifiek voor marketing gebouwd",
      "Merkgeheugen (Brand Voice)",
      "Honderden templates",
      "SEO-integratie (Surfer SEO)",
      "Teamfuncties",
    ],
    cons: [
      "Duurder dan generieke AI-tools",
      "Geen gratis tier",
      "Vereist prompt-vaardigheden",
    ],
    features: [
      "Brand Voice",
      "50+ talen",
      "SEO modus",
      "Campaign builder",
      "API toegang",
      "Teamworkspace",
    ],
    bestFor: "Marketing teams en content creators",
    publishedAt: "2024-03-01",
    updatedAt: "2024-04-01",
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI-programmeerassistent voor ontwikkelaars",
    description:
      "GitHub Copilot is de standaard AI-codeertool voor ontwikkelaars. Integreert naadloos in VS Code, JetBrains en meer. Schrijft complete functies op basis van commentaar.",
    logo: "/logos/copilot.svg",
    website: "https://github.com/features/copilot",
    affiliateUrl: "https://github.com/features/copilot?ref=besteai",
    category: ["Coderen", "Ontwikkeling"],
    pricing: {
      free: true,
      freeTier: "Gratis voor studenten & open source",
      startingPrice: "10",
      currency: "USD",
    },
    rating: 4.7,
    pros: [
      "Integreert in je IDE",
      "Ondersteunt 30+ programmeertalen",
      "Gratis voor studenten",
      "Autocomplete van hele functies",
      "Copilot Chat voor vragen",
    ],
    cons: [
      "Kan verouderde code suggereren",
      "Vereist GitHub-account",
      "Soms te veel onjuiste suggesties",
    ],
    features: [
      "IDE integratie",
      "Chat interface",
      "Multi-line autocomplete",
      "Pull request samenvatting",
      "CLI ondersteuning",
    ],
    bestFor: "Softwareontwikkelaars van alle niveaus",
    badge: "Aanbevolen",
    publishedAt: "2024-01-25",
    updatedAt: "2024-04-01",
  },
  {
    slug: "languagetool",
    name: "LanguageTool",
    tagline: "De beste grammaticacheck voor Nederlands en 30+ talen",
    description:
      "LanguageTool is een open-source grammatica- en spellingchecker die uitblinkt in Nederlandstalige teksten. Ideaal voor iedereen die foutloos wil schrijven in meerdere talen.",
    logo: "/logos/languagetool.svg",
    website: "https://languagetool.org",
    affiliateUrl: "https://languagetool.org/?ref=spotlighttool",
    category: ["Schrijven", "Grammatica", "Productiviteit"],
    pricing: {
      free: true,
      freeTier: "Gratis voor basis grammaticacheck",
      startingPrice: "4.99",
      currency: "EUR",
    },
    rating: 4.6,
    pros: [
      "Beste Nederlandse grammaticacheck op de markt",
      "Ondersteunt 30+ talen inclusief Duits, Frans, Spaans",
      "Browser-extensie voor Chrome, Firefox, Edge",
      "Open-source kern — privacy-vriendelijk",
      "Gratis basisversie uitstekend bruikbaar",
    ],
    cons: [
      "Minder AI-gestuurde stijlsuggesties dan ProWritingAid",
      "Premium is nodig voor geavanceerde stijlregels",
      "Minder inzicht in schrijfpatronen",
    ],
    features: [
      "Grammatica- en spellingcheck",
      "Nederlandstalige ondersteuning",
      "Browser-extensie",
      "Microsoft Word & Google Docs add-in",
      "Synoniemenvoorstellen",
      "API voor ontwikkelaars",
    ],
    bestFor: "Nederlandstalige schrijvers, studenten en professionals",
    badge: "Aanbevolen",
    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
  {
    slug: "prowritingaid",
    name: "ProWritingAid",
    tagline: "Diepgaande AI-schrijfcoach voor serieuze schrijvers",
    description:
      "ProWritingAid combineert grammaticacheck met gedetailleerde stijlanalyse en schrijfcoaching. Perfect voor auteurs, contentmakers en iedereen die zijn schrijfstijl structureel wil verbeteren.",
    logo: "/logos/prowritingaid.svg",
    website: "https://prowritingaid.com",
    affiliateUrl: "https://prowritingaid.com/?ref=spotlighttool",
    category: ["Schrijven", "Grammatica", "Productiviteit"],
    pricing: {
      free: true,
      freeTier: "Gratis (500 woorden per check)",
      startingPrice: "10",
      currency: "USD",
    },
    rating: 4.5,
    pros: [
      "25+ gedetailleerde schrijfrapporten",
      "Stijlanalyse en leesbaarheidsscore",
      "Integratie met Scrivener, Word, Google Docs",
      "Uitstekend voor lange teksten (boeken, rapporten)",
      "Levenslange licentie beschikbaar",
    ],
    cons: [
      "Interface kan overweldigend zijn voor beginners",
      "Minder sterk in niet-Engelse talen",
      "Gratis versie sterk beperkt (500 woorden)",
    ],
    features: [
      "Grammatica- en spellingcheck",
      "Stijl- en leesbaarheidsanalyse",
      "Passieve-stem detectie",
      "Woordherhalingschecker",
      "Scrivener & Word integratie",
      "Plagiaatcheck (premium)",
    ],
    bestFor: "Auteurs, bloggers en contentprofessionals die Engelstalig schrijven",

    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    tagline: "Snelste en betrouwbaarste VPN met wereldwijde dekking",
    description:
      "NordVPN is de marktleider in VPN-diensten met meer dan 6.000 servers in 111 landen. Ideaal voor privacy, streaming en veilig internetten op openbare netwerken.",
    logo: "/logos/nordvpn.svg",
    website: "https://nordvpn.com",
    affiliateUrl: "https://nordvpn.com/?ref=spotlighttool",
    category: ["Privacy", "VPN", "Beveiliging"],
    pricing: {
      free: false,
      startingPrice: "3.39",
      currency: "USD",
    },
    rating: 4.7,
    pros: [
      "6.000+ servers in 111 landen",
      "Geen logboekbeleid — geauditeerd",
      "Uitstekende snelheid (NordLynx protocol)",
      "Werkt met Netflix, Disney+, HBO Max",
      "Threat Protection blokkeert malware en trackers",
    ],
    cons: [
      "Geen gratis versie",
      "Desktop-app kan buggy zijn op oudere macOS",
      "Automatisch verlengd abonnement — let op",
    ],
    features: [
      "NordLynx (WireGuard) protocol",
      "Kill switch",
      "Split tunneling",
      "Threat Protection",
      "Dubbele VPN",
      "Tor over VPN",
    ],
    bestFor: "Privacy-bewuste gebruikers en streamingfans",
    badge: "Aanbevolen",
    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
  {
    slug: "themeisle",
    name: "ThemeIsle",
    tagline: "Betaalbare WordPress-thema's voor professionele websites",
    description:
      "ThemeIsle biedt WordPress-thema's en plugins voor ondernemers en ontwikkelaars die snel een professionele website willen bouwen zonder te betalen voor dure maatwerk-ontwikkeling.",
    logo: "/logos/themeisle.svg",
    website: "https://themeisle.com",
    affiliateUrl: "https://themeisle.com/?ref=spotlighttool",
    category: ["WordPress", "Webdesign", "Productiviteit"],
    pricing: {
      free: true,
      freeTier: "Gratis Neve-thema beschikbaar",
      startingPrice: "69",
      currency: "USD",
    },
    rating: 4.4,
    pros: [
      "Neve is het snelste gratis WordPress-thema",
      "Grote bibliotheek aan kant-en-klare starter sites",
      "Uitstekende compatibiliteit met Elementor & Gutenberg",
      "Actieve community en goede support",
      "Betaalbaar voor wat je krijgt",
    ],
    cons: [
      "Geavanceerde functies alleen in premium",
      "Minder bekend dan Divi of Astra",
      "Beperkte customizer opties in gratis versie",
    ],
    features: [
      "Neve WordPress-thema",
      "Starter-site templates",
      "Elementor & Gutenberg-ready",
      "WooCommerce ondersteuning",
      "Orbit Fox plugin inbegrepen",
      "Regelmatige updates",
    ],
    bestFor: "Ondernemers en freelancers die snel een WordPress-site willen",

    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
  {
    slug: "wpforms",
    name: "WPForms",
    tagline: "De makkelijkste formulierenbouwer voor WordPress",
    description:
      "WPForms is de populairste drag-and-drop formulierenbouwer voor WordPress. Van contactformulieren tot betalingen en enquêtes — in minuten live.",
    logo: "/logos/wpforms.svg",
    website: "https://wpforms.com",
    affiliateUrl: "https://wpforms.com/?ref=spotlighttool",
    category: ["WordPress", "Formulieren", "Productiviteit"],
    pricing: {
      free: true,
      freeTier: "Gratis basisversie (WPForms Lite)",
      startingPrice: "49.50",
      currency: "USD",
    },
    rating: 4.6,
    pros: [
      "Eenvoudige drag-and-drop interface",
      "6.000+ formuliertemplates",
      "Integraties met Mailchimp, Stripe, PayPal",
      "GDPR-compliant",
      "Uitstekende documentatie en support",
    ],
    cons: [
      "Geavanceerde functies (betalingen) alleen in premium",
      "Kan zwaar zijn op gedeelde hosting",
      "Jaarlijks abonnement verplicht",
    ],
    features: [
      "Drag-and-drop formulierbouwer",
      "Voorwaardelijke logica",
      "Betalingsintegraties (Stripe, PayPal)",
      "E-mailmarketing integraties",
      "Anti-spam bescherming",
      "Mobiel-responsief",
    ],
    bestFor: "WordPress-website-eigenaren die eenvoudig formulieren willen bouwen",

    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
  {
    slug: "cloudways",
    name: "Cloudways",
    tagline: "Beheerde cloud hosting voor WordPress en PHP apps",
    description:
      "Cloudways biedt beheerde cloud hosting op AWS, Google Cloud en DigitalOcean — zonder de complexiteit van server-beheer. Ideaal voor groeiende WordPress-sites en bureaus.",
    logo: "/logos/cloudways.svg",
    website: "https://cloudways.com",
    affiliateUrl: "https://cloudways.com/?ref=spotlighttool",
    category: ["Hosting", "Cloud", "WordPress"],
    pricing: {
      free: false,
      startingPrice: "14",
      currency: "USD",
    },
    rating: 4.6,
    pros: [
      "Keuze uit 5 cloud providers (AWS, GCP, DO, Vultr, Linode)",
      "Geautomatiseerde backups en SSL",
      "Uitstekende prestaties via Cloudflare Enterprise CDN",
      "Pay-as-you-go prijsmodel",
      "Eenvoudig schalen zonder downtime",
    ],
    cons: [
      "Geen gratis plan (wel 3-daagse proefperiode)",
      "Duurder dan gedeelde hosting",
      "E-mailhosting niet inbegrepen",
    ],
    features: [
      "Beheerde WordPress-hosting",
      "Cloudflare Enterprise CDN",
      "Automatische backups",
      "Gratis SSL-certificaten",
      "1-klik staging",
      "24/7 live chat support",
    ],
    bestFor: "WordPress-bureaus en groeiende e-commerce sites",

    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category.includes(category));
}

export function getAllCategories(): string[] {
  const cats = new Set<string>();
  tools.forEach((t) => t.category.forEach((c) => cats.add(c)));
  return Array.from(cats).sort();
}
