export interface Tool {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  website: string;
  affiliateUrl: string;
  price: string;
  priceDetails: string;
  categories: string[];
  rating: number;
  pros: string[];
  cons: string[];
  badge?: string;
}

export const tools: Tool[] = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "The world's most popular AI chatbot",
    description:
      "ChatGPT by OpenAI is the most widely used AI assistant. Perfect for writing, coding, analysis, and much more. With GPT-4 you get powerful results for virtually any task.",
    website: "openai.com",
    affiliateUrl: "https://chat.openai.com/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free basic version available. ChatGPT Plus for $20/month.",
    categories: ["writing", "automation", "research"],
    rating: 4.8,
    pros: ["Most versatile", "Large community", "Excellent coding support", "Plugin ecosystem"],
    cons: ["Free version limited", "Occasionally slow responses", "Privacy concerns"],
    badge: "Most Popular",
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Safe and accurate AI by Anthropic",
    description:
      "Claude by Anthropic is known for its safe, nuanced responses and excellent writing quality. Ideal for long documents and complex analyses.",
    website: "anthropic.com",
    affiliateUrl: "https://claude.ai/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free basic version. Claude Pro for $20/month with more capacity.",
    categories: ["writing", "research", "automation"],
    rating: 4.7,
    pros: ["Large context window", "High writing quality", "Safety-focused", "Nuanced answers"],
    cons: ["Fewer plugins", "No image generation", "Sometimes too cautious"],
    badge: "Best Quality",
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "Professional AI image generation",
    description:
      "Midjourney is the gold standard for AI-generated images. Create stunning illustrations, concept art, and marketing visuals with simple text prompts.",
    website: "midjourney.com",
    affiliateUrl: "https://midjourney.com/?ref=besteai",
    price: "From $10/mo",
    priceDetails: "Basic plan $10/month. Standard $30/month for more usage.",
    categories: ["images", "design"],
    rating: 4.9,
    pros: ["Best image quality", "Artistic styles", "Active community", "V6 model impressive"],
    cons: ["Discord only", "No free tier", "Learning curve"],
    badge: "Best Images",
  },
  {
    slug: "gemini",
    name: "Gemini",
    tagline: "Google's powerful multimodal AI",
    description:
      "Gemini by Google combines text, images, and data analysis in one powerful tool. Seamless integration with Google Workspace makes it ideal for business use.",
    website: "gemini.google.com",
    affiliateUrl: "https://gemini.google.com/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free with Google account. Gemini Advanced for $20/month.",
    categories: ["writing", "research", "automation"],
    rating: 4.5,
    pros: ["Google integration", "Multimodal", "Generous free tier", "Real-time info"],
    cons: ["Less creative than GPT-4", "Google privacy", "Sometimes inconsistent"],
  },
  {
    slug: "jasper",
    name: "Jasper",
    tagline: "AI for professional marketing copy",
    description:
      "Jasper is built specifically for marketing teams. Write blog posts, ads, emails, and social media content in your brand's voice.",
    website: "jasper.ai",
    affiliateUrl: "https://jasper.ai/?ref=besteai",
    price: "$49/mo",
    priceDetails: "Creator plan $49/month. Teams plan $125/month for 3 users.",
    categories: ["writing", "marketing"],
    rating: 4.3,
    pros: ["Marketing-optimised", "Brand voice", "Template library", "Team features"],
    cons: ["Expensive for solo use", "Less flexible", "Requires good prompts"],
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "Fast marketing copy in seconds",
    description:
      "Copy.ai generates marketing copy, product descriptions, and social media posts at lightning speed. Hundreds of templates get you productive instantly.",
    website: "copy.ai",
    affiliateUrl: "https://copy.ai/?ref=besteai",
    price: "Free / $36/mo",
    priceDetails: "Free plan with 2,000 words/month. Pro plan $36/month.",
    categories: ["writing", "marketing"],
    rating: 4.2,
    pros: ["Many templates", "User-friendly", "Fast output", "Good free tier"],
    cons: ["Less nuanced", "Repetition in long texts", "Limited customisation"],
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    tagline: "AI search engine with sources",
    description:
      "Perplexity combines AI with real-time web searches. Get accurate answers with source citations — ideal for research and fact-checking.",
    website: "perplexity.ai",
    affiliateUrl: "https://perplexity.ai/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free basic version. Perplexity Pro for $20/month with more searches.",
    categories: ["research", "automation"],
    rating: 4.6,
    pros: ["Real-time sources", "Great free tier", "Accurate answers", "Clean interface"],
    cons: ["Less creative", "Depends on internet", "Pro pricey for heavy use"],
    badge: "Best Research",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Realistic AI voices and audio",
    description:
      "ElevenLabs creates stunningly realistic AI voices for podcasts, videos, and apps. Clone your own voice or choose from hundreds of professional voices.",
    website: "elevenlabs.io",
    affiliateUrl: "https://elevenlabs.io/?ref=besteai",
    price: "Free / $5/mo",
    priceDetails: "Free plan with 10,000 characters/month. Starter $5/month for more.",
    categories: ["audio", "automation"],
    rating: 4.7,
    pros: ["Most realistic voices", "Voice clone feature", "API available", "Multiple languages"],
    cons: ["Free tier limited", "Ethical concerns with voice cloning", "Expensive at high volume"],
    badge: "Best Audio",
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI-powered productivity and writing inside Notion",
    description:
      "Notion AI brings artificial intelligence directly into your Notion workspace. Draft documents, summarize notes, generate action items, and brainstorm ideas without leaving your workflow.",
    website: "notion.so",
    affiliateUrl: "https://notion.so/?ref=besteai",
    price: "$10/mo",
    priceDetails: "Notion AI add-on costs $10/month per member on top of any Notion plan.",
    categories: ["writing", "automation"],
    rating: 4.5,
    pros: ["Integrated into Notion workspace", "Great for note-taking and docs", "Summarization and action items", "Collaborative"],
    cons: ["Requires Notion subscription", "Not standalone", "Limited compared to dedicated AI tools"],
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI writing assistant for flawless English",
    description:
      "Grammarly is the leading AI-powered writing assistant. It checks grammar, spelling, clarity, tone, and plagiarism in real-time across browsers, documents, and email clients.",
    website: "grammarly.com",
    affiliateUrl: "https://grammarly.com/?ref=besteai",
    price: "Free / $30/mo",
    priceDetails: "Free plan covers basic grammar. Premium $30/month for advanced suggestions and plagiarism detection.",
    categories: ["writing"],
    rating: 4.6,
    pros: ["Works everywhere (browser, Word, Gmail)", "Real-time suggestions", "Tone detection", "Great free tier"],
    cons: ["Premium is pricey", "Can over-correct style", "Privacy concerns for sensitive docs"],
    badge: "Best Grammar",
  },
  {
    slug: "canva-ai",
    name: "Canva AI",
    tagline: "AI-powered design for everyone",
    description:
      "Canva AI brings powerful design intelligence to the world's most popular design platform. Generate images, write copy, remove backgrounds, and create stunning visuals with no design experience needed.",
    website: "canva.com",
    affiliateUrl: "https://canva.com/?ref=besteai",
    price: "Free / $15/mo",
    priceDetails: "Free plan available. Canva Pro $15/month unlocks AI features and premium assets.",
    categories: ["design", "images"],
    rating: 4.7,
    pros: ["Beginner-friendly", "Huge template library", "AI image generation included", "Great free tier"],
    cons: ["Less powerful than Midjourney for pure image gen", "Pro needed for best AI features", "Can feel limiting for advanced designers"],
    badge: "Best Design",
  },
  {
    slug: "runway-ml",
    name: "Runway ML",
    tagline: "AI video and image generation for creatives",
    description:
      "Runway ML is a cutting-edge creative AI platform for video generation, image editing, and visual effects. Used by filmmakers and content creators to produce professional-grade AI video.",
    website: "runwayml.com",
    affiliateUrl: "https://runwayml.com/?ref=besteai",
    price: "From $15/mo",
    priceDetails: "Standard plan from $15/month. Pro plan $35/month for more credits and features.",
    categories: ["images", "design"],
    rating: 4.4,
    pros: ["Best AI video generation", "Professional-grade output", "Active development", "Used in Hollywood productions"],
    cons: ["Expensive for heavy use", "Learning curve", "Credits run out fast"],
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    tagline: "AI meeting transcription and notes",
    description:
      "Otter.ai automatically transcribes meetings, interviews, and lectures in real-time. Get AI-generated summaries, action items, and searchable transcripts for every conversation.",
    website: "otter.ai",
    affiliateUrl: "https://otter.ai/?ref=besteai",
    price: "Free / $17/mo",
    priceDetails: "Free plan includes 300 minutes/month. Pro $17/month for 1,200 minutes and advanced features.",
    categories: ["audio", "automation"],
    rating: 4.3,
    pros: ["Real-time transcription", "Zoom/Meet/Teams integration", "Speaker identification", "Searchable transcripts"],
    cons: ["Free tier limited", "Accuracy varies with accents", "Not ideal for noisy environments"],
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with virtual presenters",
    description:
      "Synthesia lets you create professional AI-generated videos with realistic virtual avatars. No camera or studio needed — just type your script and pick an avatar. Perfect for training videos and product demos.",
    website: "synthesia.io",
    affiliateUrl: "https://synthesia.io/?ref=besteai",
    price: "From $29/mo",
    priceDetails: "Starter plan $29/month for 10 minutes of video. Creator plan $89/month for more.",
    categories: ["automation"],
    rating: 4.4,
    pros: ["No camera needed", "120+ languages", "Professional avatars", "Easy script-to-video workflow"],
    cons: ["Expensive for high volume", "Avatars can look uncanny", "Limited customization on lower tiers"],
  },
  {
    slug: "copy-ai-2",
    name: "Copy.ai",
    tagline: "AI copywriting for marketers and teams",
    description:
      "Copy.ai is an AI-powered copywriting platform built for marketing teams. Generate blog posts, social media content, email sequences, and ad copy at scale using advanced AI workflows.",
    website: "copy.ai",
    affiliateUrl: "https://copy.ai/?ref=besteai",
    price: "Free / $49/mo",
    priceDetails: "Free plan with 2,000 words/month. Pro plan $49/month for unlimited words and workflows.",
    categories: ["writing", "marketing"],
    rating: 4.3,
    pros: ["Marketing-focused templates", "Workflow automation", "Team collaboration", "Good free tier"],
    cons: ["Quality varies", "Can be repetitive", "Pro is pricey for solo users"],
  },
  {
    slug: "deepl",
    name: "DeepL",
    tagline: "The world's most accurate AI translator",
    description:
      "DeepL uses advanced neural networks to deliver the most accurate translations available. Supports 30+ languages with nuanced, natural-sounding output. Trusted by professionals and businesses worldwide.",
    website: "deepl.com",
    affiliateUrl: "https://deepl.com/?ref=besteai",
    price: "Free / $8/mo",
    priceDetails: "Free plan for casual use. DeepL Pro from $8/month for unlimited text and document translation.",
    categories: ["writing"],
    rating: 4.8,
    pros: ["Best translation accuracy", "Natural-sounding output", "Document translation", "API available"],
    cons: ["Fewer languages than Google Translate", "Pro needed for heavy use", "No image translation"],
    badge: "Best Translation",
  },
  {
    slug: "zapier-ai",
    name: "Zapier AI",
    tagline: "Automate workflows with AI-powered Zaps",
    description:
      "Zapier AI brings artificial intelligence to workflow automation. Build AI-powered automations that connect 6,000+ apps, make decisions, and handle complex logic — all without coding.",
    website: "zapier.com",
    affiliateUrl: "https://zapier.com/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free plan for basic automations. Starter $20/month for AI features and more Zaps.",
    categories: ["automation"],
    rating: 4.2,
    pros: ["6,000+ app integrations", "No-code AI automation", "Reliable and battle-tested", "Good free tier"],
    cons: ["Complex Zaps get expensive", "AI features still maturing", "Learning curve for advanced workflows"],
  },
  {
    slug: "grok",
    name: "Grok",
    tagline: "xAI's witty and unfiltered AI assistant",
    description:
      "Grok is xAI's AI assistant, integrated into X (Twitter). Known for its wit, real-time access to X posts, and willingness to answer edgier questions. Great for research, brainstorming, and staying current.",
    website: "x.ai",
    affiliateUrl: "https://x.ai/?ref=besteai",
    price: "Free / $16/mo",
    priceDetails: "Available free on X. X Premium+ at $16/month unlocks full Grok access.",
    categories: ["research", "writing"],
    rating: 4.3,
    pros: ["Real-time X/Twitter data", "Less censored responses", "Witty personality", "Strong reasoning model (Grok-3)"],
    cons: ["Requires X Premium for full access", "Smaller ecosystem than OpenAI", "Less polished than ChatGPT"],
  },
];

export const categories = [
  { slug: "writing", name: "Writing & Text", icon: "✍️", description: "AI tools for blog posts, copywriting and content creation" },
  { slug: "video", name: "Video & Presentation", icon: "🎬", description: "AI tools for video creation, editing and avatars" },
  { slug: "images", name: "Images & Design", icon: "🎨", description: "Generate professional visuals with AI" },
  { slug: "automation", name: "Automation", icon: "⚡", description: "Automate your workflows with AI" },
  { slug: "research", name: "Research & Analysis", icon: "🔍", description: "AI-powered research and data analysis" },
  { slug: "marketing", name: "Marketing & Sales", icon: "📈", description: "Boost your marketing with AI copywriting" },
  { slug: "audio", name: "Audio & Voice", icon: "🎙️", description: "AI-generated voices and audio content" },
  { slug: "design", name: "Design & Creativity", icon: "🖌️", description: "Creative tools for designers" },
];

// New tools appended below
// Additional tools
const extraTools: Tool[] = [
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "AI image generation built into Adobe Creative Cloud",
    description: "Adobe Firefly brings generative AI directly into Adobe's creative apps. Generate images, fill objects, and design assets using text prompts — fully integrated with Photoshop, Illustrator, and more.",
    website: "firefly.adobe.com",
    affiliateUrl: "https://firefly.adobe.com/?ref=besteai",
    price: "Free / $5/mo",
    priceDetails: "Free with limited credits. Firefly premium from $5/month.",
    categories: ["images", "design"],
    rating: 4.5,
    pros: ["Integrated with Adobe apps", "Commercial-safe images", "Generative fill in Photoshop", "Good free tier"],
    cons: ["Credits run out quickly", "Requires Adobe account", "Less artistic than Midjourney"],
  },
  {
    slug: "stable-diffusion",
    name: "Stable Diffusion (DreamStudio)",
    tagline: "Open-source AI image generation at your fingertips",
    description: "Stable Diffusion via DreamStudio is one of the most powerful open-source AI image generators. Run it in the cloud via DreamStudio or locally for full control over your image generation.",
    website: "dreamstudio.ai",
    affiliateUrl: "https://dreamstudio.ai/?ref=besteai",
    price: "Free / $10/mo",
    priceDetails: "Free credits on signup. DreamStudio top-up from $10.",
    categories: ["images"],
    rating: 4.3,
    pros: ["Open-source and flexible", "Run locally for free", "Huge community", "ControlNet and fine-tuning support"],
    cons: ["Technical setup for local use", "Less polished than Midjourney", "Requires prompt engineering"],
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI coding assistant by GitHub and OpenAI",
    description: "GitHub Copilot is the world's most popular AI coding assistant. Get real-time code suggestions, auto-complete entire functions, and chat with AI about your codebase — all inside VS Code and other editors.",
    website: "github.com/features/copilot",
    affiliateUrl: "https://github.com/features/copilot?ref=besteai",
    price: "$10/mo",
    priceDetails: "Individual plan $10/month. Business plan $19/month per user.",
    categories: ["automation"],
    rating: 4.7,
    pros: ["Best code completion", "Integrated in VS Code", "GitHub context awareness", "Chat mode available"],
    cons: ["No free tier for most users", "Can suggest insecure code", "Requires GitHub account"],
    badge: "Best Coding",
  },
  {
    slug: "cursor-ai",
    name: "Cursor AI",
    tagline: "The AI-first code editor for 10x developers",
    description: "Cursor is a VS Code fork with deep AI integration. Chat with your entire codebase, apply multi-file edits, and generate code with GPT-4 and Claude — built for developers who want AI at the center of their workflow.",
    website: "cursor.com",
    affiliateUrl: "https://cursor.com/?ref=besteai",
    price: "Free / $20/mo",
    priceDetails: "Free hobby plan available. Pro $20/month with unlimited AI usage.",
    categories: ["automation"],
    rating: 4.6,
    pros: ["Codebase-aware AI", "Multi-file editing", "VS Code compatible", "Claude and GPT-4 built-in"],
    cons: ["Learning curve", "Pro needed for heavy use", "Relatively new tool"],
  },
  {
    slug: "heygen",
    name: "HeyGen",
    tagline: "Create AI avatar videos at scale",
    description: "HeyGen enables businesses to create professional AI avatar videos in minutes. Clone yourself, choose from 100+ avatars, and generate videos in 40+ languages — perfect for training, marketing, and sales content.",
    website: "heygen.com",
    affiliateUrl: "https://heygen.com/?ref=besteai",
    price: "$29/mo",
    priceDetails: "Creator plan $29/month. Business plan $89/month for more features.",
    categories: ["video", "images"],
    rating: 4.3,
    pros: ["Realistic avatars", "40+ languages", "Avatar voice cloning", "API available"],
    cons: ["No free tier", "Avatars can look robotic", "Expensive for high volume"],
  },
  {
    slug: "murf-ai",
    name: "Murf AI",
    tagline: "Studio-quality AI voices for any content",
    description: "Murf AI is a professional text-to-speech platform with 120+ ultra-realistic voices in 20+ languages. Create voiceovers for videos, podcasts, e-learning, and presentations without a studio.",
    website: "murf.ai",
    affiliateUrl: "https://murf.ai/?ref=besteai",
    price: "Free / $19/mo",
    priceDetails: "Free plan with 10 minutes/month. Creator plan $19/month for more voice time.",
    categories: ["audio"],
    rating: 4.4,
    pros: ["120+ voices", "20+ languages", "Video sync feature", "Easy-to-use editor"],
    cons: ["Free tier very limited", "Not as natural as ElevenLabs", "No voice cloning on lower tiers"],
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "AI writing and marketing content at scale",
    description: "Writesonic is an AI writing platform for marketers and content teams. Generate blog posts, ads, product descriptions, and landing pages with AI trained on top-performing marketing content.",
    website: "writesonic.com",
    affiliateUrl: "https://writesonic.com/?ref=besteai",
    price: "Free / $16/mo",
    priceDetails: "Free plan with limited words. Small Team plan $16/month for 200K words.",
    categories: ["writing", "marketing"],
    rating: 4.3,
    pros: ["Marketing-focused content", "Factual article writer", "Integrates with Surfer SEO", "Good free tier"],
    cons: ["Quality inconsistent", "Can sound generic", "Limited advanced features on free"],
  },
  {
    slug: "semrush-ai",
    name: "Semrush AI",
    tagline: "AI-powered SEO and marketing intelligence",
    description: "Semrush is the leading all-in-one SEO and marketing platform, now enhanced with AI. Get keyword research, competitor analysis, site audits, and AI-generated content recommendations to dominate search rankings.",
    website: "semrush.com",
    affiliateUrl: "https://semrush.com/?ref=besteai",
    price: "$120/mo",
    priceDetails: "Pro plan $120/month. Guru $230/month for advanced features.",
    categories: ["marketing", "research"],
    rating: 4.5,
    pros: ["Industry-leading SEO data", "Competitor analysis", "AI content tools", "All-in-one platform"],
    cons: ["Expensive", "Overwhelming for beginners", "Data can lag for small sites"],
    badge: "Best SEO",
  },
  {
    slug: "loom-ai",
    name: "Loom AI",
    tagline: "Record, share and transcribe videos with AI",
    description: "Loom AI supercharges screen recording with artificial intelligence. Auto-transcribe videos, generate summaries and titles, remove filler words, and turn recordings into async communication that actually gets watched.",
    website: "loom.com",
    affiliateUrl: "https://loom.com/?ref=besteai",
    price: "Free / $12/mo",
    priceDetails: "Free plan with 25 videos. Business plan $12/month per user for unlimited recordings.",
    categories: ["video", "images"],
    rating: 4.4,
    pros: ["AI transcription included", "Auto-generated summaries", "Easy screen recording", "Good free tier"],
    cons: ["Storage limits on free", "Limited video editing", "Requires team for full value"],
  },
];

// Sprint 3 tools
const sprint3Tools: Tool[] = [
  {
    slug: "leonardo-ai",
    name: "Leonardo AI",
    tagline: "High-quality AI image generation for creatives",
    description:
      "Leonardo AI delivers stunning, consistent AI-generated images for game assets, concept art, and marketing. Its fine-tuning and canvas tools make it a favourite among professional creatives.",
    website: "leonardo.ai",
    affiliateUrl: "https://leonardo.ai/?ref=besteai",
    price: "Free / $12/mo",
    priceDetails: "Free tier with 150 daily tokens. Apprentice plan $12/month for more generations.",
    categories: ["images"],
    rating: 4.4,
    pros: ["Consistent character styles", "Fine-tuning support", "Generous free tier", "Canvas editor"],
    cons: ["Watermark on free plan", "Can be slow at peak times", "Learning curve for fine-tuning"],
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Edit audio and video by editing text",
    description:
      "Descript lets you edit podcasts and videos as easily as a Word document. AI-powered features include automatic transcription, filler-word removal, and voice cloning.",
    website: "descript.com",
    affiliateUrl: "https://descript.com/?ref=besteai",
    price: "Free / $24/mo",
    priceDetails: "Free plan with 1 hour transcription. Creator plan $24/month for unlimited transcription.",
    categories: ["audio", "video"],
    rating: 4.4,
    pros: ["Text-based editing", "AI filler-word removal", "Voice clone (Overdub)", "Collaborative"],
    cons: ["Steep learning curve", "Expensive for casual use", "Exports can be slow"],
  },
  {
    slug: "pika-labs",
    name: "Pika Labs",
    tagline: "Turn ideas into cinematic AI videos",
    description:
      "Pika Labs generates short, high-quality AI videos from text prompts or images. Known for its smooth motion and cinematic style, it's a top pick for content creators and marketers.",
    website: "pika.art",
    affiliateUrl: "https://pika.art/?ref=besteai",
    price: "Free / $8/mo",
    priceDetails: "Free tier available. Basic plan $8/month for more monthly generations.",
    categories: ["video"],
    rating: 4.2,
    pros: ["Easy text-to-video", "Smooth motion", "Affordable plans", "Active community"],
    cons: ["Short clip lengths", "Limited control over details", "Queue times on free tier"],
  },
  {
    slug: "sora-openai",
    name: "Sora",
    tagline: "OpenAI's groundbreaking text-to-video model",
    description:
      "Sora by OpenAI generates photorealistic, complex video scenes from text descriptions. It represents a leap forward in AI video quality and temporal consistency.",
    website: "openai.com/sora",
    affiliateUrl: "https://openai.com/sora?ref=besteai",
    price: "Free / waitlist",
    priceDetails: "Available to ChatGPT Plus and Pro subscribers. Broader access rolling out.",
    categories: ["video"],
    rating: 4.5,
    pros: ["Photorealistic quality", "Long coherent scenes", "Complex motion", "OpenAI ecosystem"],
    cons: ["Limited availability", "No fine-tuning yet", "High compute cost"],
    badge: "New",
  },
  {
    slug: "character-ai",
    name: "Character.AI",
    tagline: "Chat with AI characters and create your own",
    description:
      "Character.AI lets you chat with thousands of AI personas — from historical figures to fictional characters — or build your own. Perfect for entertainment, storytelling, and roleplay.",
    website: "character.ai",
    affiliateUrl: "https://character.ai/?ref=besteai",
    price: "Free / $10/mo",
    priceDetails: "Free with ads and slower responses. c.ai+ at $10/month for priority access.",
    categories: ["writing", "research"],
    rating: 4.1,
    pros: ["Massive character library", "Easy persona creation", "Entertaining and immersive", "Free tier available"],
    cons: ["Content filters can be limiting", "Not for serious productivity", "Occasional inconsistencies"],
  },
  {
    slug: "nightcafe",
    name: "NightCafe",
    tagline: "AI art generator with a creative community",
    description:
      "NightCafe is one of the most accessible AI art platforms, supporting multiple models including Stable Diffusion and DALL-E. Its credit system and active community make it great for beginners.",
    website: "nightcafe.studio",
    affiliateUrl: "https://nightcafe.studio/?ref=besteai",
    price: "Free / $6/mo",
    priceDetails: "Free daily credits. Starter plan $6/month for more credits and features.",
    categories: ["images"],
    rating: 4.2,
    pros: ["Multiple AI models", "Active community", "Very affordable", "Good for beginners"],
    cons: ["Lower max resolution than rivals", "Credit system can confuse", "Less control than Midjourney"],
  },
  {
    slug: "wordtune",
    name: "Wordtune",
    tagline: "AI writing companion that rewrites and improves your text",
    description:
      "Wordtune helps you rephrase, shorten, expand, and improve any text in seconds. It's the go-to AI writing assistant for non-native English speakers and busy professionals.",
    website: "wordtune.com",
    affiliateUrl: "https://wordtune.com/?ref=besteai",
    price: "Free / $14/mo",
    priceDetails: "Free plan with 10 rewrites/day. Plus plan $14/month for unlimited rewrites.",
    categories: ["writing"],
    rating: 4.3,
    pros: ["Instant rephrasing", "Tone adjustment", "Browser extension", "Great for ESL writers"],
    cons: ["Focused mainly on rephrasing", "Limited content generation", "Free tier restrictive"],
  },
  {
    slug: "beautiful-ai",
    name: "Beautiful.ai",
    tagline: "AI-powered presentations that design themselves",
    description:
      "Beautiful.ai automates slide design so you can focus on content. Smart templates adapt as you type, ensuring every presentation looks polished and professional.",
    website: "beautiful.ai",
    affiliateUrl: "https://beautiful.ai/?ref=besteai",
    price: "$12/mo",
    priceDetails: "Pro plan $12/month billed annually. Team plans available for collaboration.",
    categories: ["design"],
    rating: 4.3,
    pros: ["Auto-adapting layouts", "Beautiful templates", "Easy to use", "Good brand controls"],
    cons: ["No free tier", "Less flexible than PowerPoint", "Export options limited"],
  },
];

tools.push(...sprint3Tools);

// Merge extra tools into main array
tools.push(...extraTools);

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.categories.includes(categorySlug));
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}
